### ISSUE TITLE
Routing Problem

### ISSUE THREAD

**Issue by Abhishekkange** [Abhishekkange/NearbyKart-Admin-Reactjs#8]
Whenever we navigate to '/' - Then Main Screen will open . Then if user is logged in then when we use '/admin' we will navigate to Dashboard. And after that then apply the routes like '/admin/Home' , '/admin/Bulk Products', 
Then we can have a '/signup' and '/login' Page.

**Comment by AdityaNik** [comment]
@Abhishekkange backend part is already done n
just need to hit the backend api
